export const ADMIN_DB_SCHEMA_VERSION = "GPMS_DATABASE_V2.1";

export const ADMIN_DB_PERMISSION_CORE_TABLES = [
  {
    table: "[ROLE]",
    label: "Role Catalog",
    columns: "ROLE_ID, NAME",
    relation: "Master data",
    description: "Danh mục role hệ thống. Đây là lớp role chính để gán vào user.",
  },
  {
    table: "USER_ROLE",
    label: "User Role Bridge",
    columns: "USER_ID, ROLE_ID",
    relation: "Assignment bridge",
    description: "Bảng nối giữa user và role. Đây là trung tâm của quản trị quyền trong schema hiện tại.",
  },
  {
    table: "WORKER_SKILL",
    label: "Worker Skill Catalog",
    columns: "WS_ID, NAME",
    relation: "Skill catalog",
    description: "Danh mục kỹ năng/chuyên môn thợ, tách riêng với role hệ thống.",
  },
  {
    table: "USER_WORKER_SKILL",
    label: "User Worker Skill Bridge",
    columns: "USER_ID, WS_ID",
    relation: "Assignment bridge",
    description: "Bảng nối user với worker skill, phục vụ phân công chuyên môn và thống kê tay nghề.",
  },
];

export const ADMIN_DB_USER_FOREIGN_TABLES = [
  {
    table: "LEAVE_REQUEST",
    column: "USER_ID",
    module: "Leave Request",
    purpose: "Người tạo đơn nghỉ phép.",
  },
  {
    table: "[ORDER]",
    column: "USER_ID",
    module: "Orders",
    purpose: "User gắn với đơn hàng.",
  },
  {
    table: "UO_COMMENT",
    column: "FROM_USER",
    module: "Orders",
    purpose: "Người gửi bình luận vào order.",
  },
  {
    table: "ORDER_REJECT_REASON",
    column: "USER_ID",
    module: "Orders",
    purpose: "Người từ chối đơn hàng.",
  },
  {
    table: "PRODUCTION",
    column: "PM_ID",
    module: "Production",
    purpose: "PM phụ trách production.",
  },
  {
    table: "PRODUCTION_REJECT_REASON",
    column: "USER_ID",
    module: "Production",
    purpose: "Người từ chối production.",
  },
  {
    table: "UP_COMMENT",
    column: "FROM_USER",
    module: "Production",
    purpose: "Người gửi bình luận vào production.",
  },
  {
    table: "CUTTING_NOTEBOOK_LOG",
    column: "USER_ID",
    module: "Cutting",
    purpose: "Người ghi nhật ký cắt.",
  },
  {
    table: "P_PART_ASSIGNEE",
    column: "USER_ID",
    module: "Production Part",
    purpose: "Worker được gán vào công đoạn.",
  },
  {
    table: "PART_WORK_LOG",
    column: "USER_ID",
    module: "Production Part",
    purpose: "Worker ghi sản lượng theo công đoạn.",
  },
  {
    table: "[USER]",
    column: "MANAGER_ID",
    module: "User Hierarchy",
    purpose: "Phản ánh quan hệ Owner / PM / Worker theo tuyến quản lý.",
  },
  {
    table: "PRODUCTION_ISSUE_LOG",
    column: "CREATED_BY / ASSIGNED_TO",
    module: "Issue Tracking",
    purpose: "Người tạo lỗi và người được giao xử lý trong production.",
  },
];

export const ADMIN_DB_PERMISSION_GAPS = [
  {
    table: "PERMISSION",
    impact: "Chưa có bảng định nghĩa capability chi tiết theo module/action.",
  },
  {
    table: "ROLE_PERMISSION",
    impact: "Chưa thể lưu ma trận role -> permission ở tầng database.",
  },
  {
    table: "ROLE_CHANGE_AUDIT",
    impact: "Chưa có audit trail riêng cho việc đổi role hoặc thu hồi quyền.",
  },
];

export const ADMIN_DB_LOG_GAPS = [
  {
    table: "SYSTEM_LOG",
    impact: "Chưa có bảng nhật ký hợp nhất cho toàn hệ thống.",
  },
  {
    table: "LOGIN_AUDIT",
    impact: "Schema chưa lưu lịch sử đăng nhập, thất bại đăng nhập hoặc session.",
  },
  {
    table: "IP_TRACKING",
    impact: "Chưa có nguồn dữ liệu cho IP, device, geo hoặc anomaly detection.",
  },
];

export const ADMIN_DB_LOG_SOURCES = [
  {
    key: "order-history",
    table: "O_HISTORY_UPDATE",
    moduleLabel: "Orders",
    tone: "primary",
    actorMode: "missing",
    actorLabel: "Không có USER_ID",
    timeColumn: "CHANGE_AT",
    flags: ["FIELD_NAME", "OLD_VALUE", "NEW_VALUE"],
    description: "Theo dõi thay đổi field của đơn hàng nhưng không lưu actor trực tiếp.",
  },
  {
    key: "order-reject",
    table: "ORDER_REJECT_REASON",
    moduleLabel: "Orders",
    tone: "warning",
    actorMode: "user",
    actorLabel: "Có USER_ID",
    timeColumn: "CREATED_AT",
    flags: ["REASON"],
    description: "Lưu lý do từ chối đơn hàng và người thực hiện quyết định.",
  },
  {
    key: "production-reject",
    table: "PRODUCTION_REJECT_REASON",
    moduleLabel: "Production",
    tone: "warning",
    actorMode: "user",
    actorLabel: "Có USER_ID",
    timeColumn: "CREATED_AT",
    flags: ["REASON"],
    description: "Lưu lý do từ chối production và user đưa ra quyết định.",
  },
  {
    key: "leave-workflow",
    table: "LEAVE_REQUEST",
    moduleLabel: "Leave Request",
    tone: "info",
    actorMode: "user",
    actorLabel: "Có USER_ID",
    timeColumn: "DATE_CREATE / DATE_REPLY",
    flags: ["CONTENT", "DENY_CONTENT", "LRS_ID"],
    description: "Workflow nghỉ phép có trạng thái, thời điểm tạo/phản hồi và nội dung từ chối.",
  },
  {
    key: "cutting-log",
    table: "CUTTING_NOTEBOOK_LOG",
    moduleLabel: "Cutting",
    tone: "success",
    actorMode: "user",
    actorLabel: "Có USER_ID",
    timeColumn: "DATE_CREATE",
    flags: ["IS_READ_ONLY", "IS_PAYMENT"],
    description: "Nhật ký cắt vải theo sơ đồ, có cờ khóa và cờ thanh toán.",
  },
  {
    key: "part-work-log",
    table: "PART_WORK_LOG",
    moduleLabel: "Production Part",
    tone: "success",
    actorMode: "user",
    actorLabel: "Có USER_ID",
    timeColumn: "CREATE_DATE",
    flags: ["IS_READ_ONLY", "IS_PAYMENT"],
    description: "Nhật ký sản lượng công đoạn theo worker, thời điểm ghi nhận và trạng thái thanh toán.",
  },
  {
    key: "issue-log",
    table: "PRODUCTION_ISSUE_LOG",
    moduleLabel: "Issue Tracking",
    tone: "warning",
    actorMode: "user",
    actorLabel: "Có CREATED_BY / ASSIGNED_TO",
    timeColumn: "CREATED_AT",
    flags: ["TYPE_ISSUE", "PRIORITY", "IS_ID"],
    description: "Log lỗi production có người báo, người xử lý, mức độ ưu tiên và trạng thái.",
  },
];

export const ADMIN_DB_SYSTEM_LOG_EVENTS = [
  {
    id: "O_HISTORY_UPDATE-204",
    timestamp: "2026-03-15T08:42:00+07:00",
    sourceKey: "order-history",
    sourceTable: "O_HISTORY_UPDATE",
    moduleLabel: "Orders",
    action: "Cập nhật trường END_DATE",
    entityLabel: "ORDER #204",
    actorLabel: "Không lưu USER_ID",
    actorTrace: "Schema chỉ có FIELD_NAME / OLD_VALUE / NEW_VALUE.",
    detail: "END_DATE: 2026-03-18 -> 2026-03-20",
    flags: ["Field delta", "No actor"],
  },
  {
    id: "ORDER_REJECT_REASON-198",
    timestamp: "2026-03-15T07:55:00+07:00",
    sourceKey: "order-reject",
    sourceTable: "ORDER_REJECT_REASON",
    moduleLabel: "Orders",
    action: "Từ chối đơn hàng",
    entityLabel: "ORDER #198",
    actorLabel: "USER_ID #3",
    actorTrace: "Actor lấy trực tiếp từ USER_ID.",
    detail: "REASON: Thiếu rập cứng và màu vải chưa khớp.",
    flags: ["Decision", "Reason captured"],
  },
  {
    id: "PRODUCTION_REJECT_REASON-088",
    timestamp: "2026-03-15T07:24:00+07:00",
    sourceKey: "production-reject",
    sourceTable: "PRODUCTION_REJECT_REASON",
    moduleLabel: "Production",
    action: "Từ chối production",
    entityLabel: "PRODUCTION #88",
    actorLabel: "USER_ID #2",
    actorTrace: "Actor lấy trực tiếp từ USER_ID.",
    detail: "REASON: Kế hoạch sản xuất chưa đủ nguyên liệu đầu vào.",
    flags: ["Decision", "Reason captured"],
  },
  {
    id: "LEAVE_REQUEST-061",
    timestamp: "2026-03-15T06:45:00+07:00",
    sourceKey: "leave-workflow",
    sourceTable: "LEAVE_REQUEST",
    moduleLabel: "Leave Request",
    action: "Đơn nghỉ bị từ chối",
    entityLabel: "LEAVE_REQUEST #61",
    actorLabel: "USER_ID #14",
    actorTrace: "Schema lưu USER_ID của người tạo đơn; người phản hồi phải suy ra từ workflow ngoài DB.",
    detail: "DENY_CONTENT: Không đủ người thay ca trong ngày 15/03.",
    flags: ["Workflow", "Reply timestamp"],
  },
  {
    id: "CUTTING_NOTEBOOK_LOG-312",
    timestamp: "2026-03-14T16:10:00+07:00",
    sourceKey: "cutting-log",
    sourceTable: "CUTTING_NOTEBOOK_LOG",
    moduleLabel: "Cutting",
    action: "Ghi nhật ký cắt",
    entityLabel: "CP #12 / CND #312",
    actorLabel: "USER_ID #21",
    actorTrace: "Actor lấy trực tiếp từ USER_ID.",
    detail: "COLOR Navy, LAYER 18, PRODUCT_QTY 420, AVG_CONSUMPTION 1.185.",
    flags: ["IS_READ_ONLY = 1", "IS_PAYMENT = 0"],
  },
  {
    id: "PART_WORK_LOG-881",
    timestamp: "2026-03-14T15:36:00+07:00",
    sourceKey: "part-work-log",
    sourceTable: "PART_WORK_LOG",
    moduleLabel: "Production Part",
    action: "Chốt sản lượng công đoạn",
    entityLabel: "PP #55 / WL #881",
    actorLabel: "USER_ID #25",
    actorTrace: "Actor lấy trực tiếp từ USER_ID.",
    detail: "QUANTITY 320 trên CREATE_DATE 2026-03-14.",
    flags: ["IS_READ_ONLY = 0", "IS_PAYMENT = 1"],
  },
  {
    id: "PRODUCTION_ISSUE_LOG-145",
    timestamp: "2026-03-15T11:05:00+07:00",
    sourceKey: "issue-log",
    sourceTable: "PRODUCTION_ISSUE_LOG",
    moduleLabel: "Issue Tracking",
    action: "Tạo issue production",
    entityLabel: "ISSUE #145 / PRODUCTION #88",
    actorLabel: "CREATED_BY #18",
    actorTrace: "Người xử lý hiện tại lưu ở ASSIGNED_TO.",
    detail: "TYPE_ISSUE Cat, PRIORITY High, trạng thái PROCESSING.",
    flags: ["Assigned", "Priority tracked"],
  },
  {
    id: "LEAVE_REQUEST-058",
    timestamp: "2026-03-14T10:22:00+07:00",
    sourceKey: "leave-workflow",
    sourceTable: "LEAVE_REQUEST",
    moduleLabel: "Leave Request",
    action: "Tạo đơn nghỉ mới",
    entityLabel: "LEAVE_REQUEST #58",
    actorLabel: "USER_ID #19",
    actorTrace: "Nguồn actor có trong USER_ID của đơn.",
    detail: "CONTENT: Xin nghỉ 1 ngày vì lý do sức khỏe.",
    flags: ["Workflow", "Pending"],
  },
  {
    id: "O_HISTORY_UPDATE-201",
    timestamp: "2026-03-14T09:40:00+07:00",
    sourceKey: "order-history",
    sourceTable: "O_HISTORY_UPDATE",
    moduleLabel: "Orders",
    action: "Cập nhật trường QUANTITY",
    entityLabel: "ORDER #201",
    actorLabel: "Không lưu USER_ID",
    actorTrace: "Không thể lần ngược user nếu không có audit layer bổ sung.",
    detail: "QUANTITY: 1200 -> 1350",
    flags: ["Field delta", "No actor"],
  },
];

export const ADMIN_DB_ROLE_BLUEPRINTS = [
  {
    key: "Admin",
    label: "Quản trị hệ thống",
    shortLabel: "Lớp account và role",
    tone: "danger",
    description: "Vai trò quản trị account, trạng thái user và tầng role hiện có trong schema.",
    joinPath: "[ROLE] -> USER_ROLE -> [USER] -> U_STATUS",
    touchpoints: [
      {
        scope: "Direct",
        tone: "danger",
        table: "[ROLE]",
        columns: "ROLE_ID, NAME",
        relation: "Quản trị catalog role hệ thống.",
      },
      {
        scope: "Direct",
        tone: "danger",
        table: "USER_ROLE",
        columns: "USER_ID, ROLE_ID",
        relation: "Gán hoặc thu hồi role cho user.",
      },
      {
        scope: "Direct",
        tone: "primary",
        table: "[USER]",
        columns: "USER_ID, USERNAME, US_ID",
        relation: "Quản lý hồ sơ user và trạng thái account.",
      },
      {
        scope: "Direct",
        tone: "info",
        table: "U_STATUS",
        columns: "US_ID, NAME",
        relation: "Tra cứu trạng thái user.",
      },
      {
        scope: "Direct",
        tone: "warning",
        table: "WORKER_SKILL / USER_WORKER_SKILL",
        columns: "WS_ID, USER_ID",
        relation: "Quản lý kỹ năng worker song song với role hệ thống.",
      },
    ],
    gaps: [
      "Chưa có bảng PERMISSION nên chưa thể cấp capability chi tiết.",
      "Chưa có ROLE_PERMISSION để lưu cấu hình theo module/action.",
      "Chưa có audit riêng cho thay đổi role và policy.",
    ],
  },
  {
    key: "Owner",
    label: "Chủ xưởng",
    shortLabel: "Giám sát điều hành",
    tone: "warning",
    description: "Vai trò điều hành ở đỉnh business flow, theo mô hình 1 owner quản lý nhiều PM qua role và tuyến MANAGER_ID.",
    joinPath: "[ROLE] -> USER_ROLE -> [USER] -> MANAGER_ID",
    touchpoints: [
      {
        scope: "Direct",
        tone: "warning",
        table: "USER_ROLE",
        columns: "USER_ID, ROLE_ID",
        relation: "Owner chỉ được xác định trực tiếp qua table gán role.",
      },
      {
        scope: "Direct",
        tone: "info",
        table: "[USER]",
        columns: "USER_ID, MANAGER_ID",
        relation: "Owner là đỉnh tuyến quản lý; mỗi owner quản lý nhiều PM trong business flow mới.",
      },
      {
        scope: "Inferred",
        tone: "primary",
        table: "[ORDER]",
        columns: "USER_ID, OS_ID",
        relation: "Owner thường giám sát order, nhưng vẫn chưa có OWNER_ID riêng trên order.",
      },
      {
        scope: "Inferred",
        tone: "info",
        table: "LEAVE_REQUEST",
        columns: "USER_ID, LRS_ID",
        relation: "Quy trình duyệt đơn nghỉ có thể đi qua owner, nhưng schema chưa lưu approver.",
      },
      {
        scope: "Inferred",
        tone: "primary",
        table: "PRODUCTION",
        columns: "PM_ID, ORDER_ID",
        relation: "Owner giám sát production qua tuyến quản lý và workflow, chưa có cột owner trực tiếp.",
      },
    ],
    gaps: [
      "Chưa có cột OWNER_ID trực tiếp ở order/production.",
      "Chưa có bảng approval audit cho các quyết định cấp owner.",
    ],
  },
  {
    key: "PM",
    label: "Quản lý sản xuất",
    shortLabel: "Điều phối production",
    tone: "primary",
    description: "Role có dấu vết trực tiếp nhất ở bảng PRODUCTION và tuyến quản lý team lead, worker qua MANAGER_ID.",
    joinPath: "[ROLE] -> USER_ROLE -> [USER] -> PRODUCTION.PM_ID",
    touchpoints: [
      {
        scope: "Direct",
        tone: "primary",
        table: "PRODUCTION",
        columns: "PM_ID, ORDER_ID, PS_ID",
        relation: "PM được gắn trực tiếp qua cột PM_ID.",
      },
      {
        scope: "Direct",
        tone: "info",
        table: "[USER]",
        columns: "USER_ID, MANAGER_ID",
        relation: "PM quản lý team lead và worker của line mình trong flow Owner -> PM -> Team Lead / Worker.",
      },
      {
        scope: "Workflow",
        tone: "success",
        table: "CUTTING_NOTEBOOK / CUTTING_NOTEBOOK_LOG",
        columns: "PRODUCTION_ID, USER_ID, IS_PAYMENT",
        relation: "Theo dõi log cắt và trạng thái thanh toán của khâu đầu vào.",
      },
      {
        scope: "Workflow",
        tone: "success",
        table: "PART_WORK_LOG",
        columns: "PP_ID, USER_ID, CREATE_DATE, IS_PAYMENT",
        relation: "Review sản lượng theo công đoạn để điều hành tiến độ.",
      },
      {
        scope: "Workflow",
        tone: "warning",
        table: "PRODUCTION_ISSUE_LOG",
        columns: "CREATED_BY, ASSIGNED_TO, PRIORITY, IS_ID",
        relation: "PM theo dõi và xử lý issue phát sinh trong production.",
      },
    ],
    gaps: [
      "Chưa có bảng riêng cho PM approval history.",
      "Chưa có permission matrix để tách quyền xem và quyền phê duyệt.",
    ],
  },
  {
    key: "KCS",
    label: "Kiểm soát chất lượng",
    shortLabel: "Decision và reject flow",
    tone: "success",
    description: "Role KCS hiện đi qua các bảng reject reason hơn là có bảng QC riêng.",
    joinPath: "[ROLE] -> USER_ROLE -> [USER]",
    touchpoints: [
      {
        scope: "Direct",
        tone: "warning",
        table: "ORDER_REJECT_REASON",
        columns: "ORDER_ID, USER_ID, REASON",
        relation: "Có thể lần ngược user đưa ra quyết định từ chối order.",
      },
      {
        scope: "Direct",
        tone: "warning",
        table: "PRODUCTION_REJECT_REASON",
        columns: "PRODUCTION_ID, USER_ID, REASON",
        relation: "Có thể lần ngược user đưa ra quyết định từ chối production.",
      },
      {
        scope: "Inferred",
        tone: "primary",
        table: "O_HISTORY_UPDATE",
        columns: "FIELD_NAME, OLD_VALUE, NEW_VALUE, CHANGE_AT",
        relation: "KCS có thể cần review thay đổi, nhưng bảng này chưa lưu actor.",
      },
    ],
    gaps: [
      "Schema chưa có bảng inspection detail hoặc QC checklist riêng.",
      "Không có log riêng cho quyết định pass/fail ngoài reject reason.",
    ],
  },
  {
    key: "Team Leader",
    label: "Tổ trưởng",
    shortLabel: "Điều phối chuyền",
    tone: "info",
    description: "Role vận hành vẫn tồn tại ở tầng nghiệp vụ; mỗi team lead thuộc một PM nhưng schema V2.1 chưa có cột riêng để neo trực tiếp trên part.",
    joinPath: "[ROLE] -> USER_ROLE -> [USER] -> MANAGER_ID / P_PART_ASSIGNEE",
    touchpoints: [
      {
        scope: "Inferred",
        tone: "info",
        table: "[USER]",
        columns: "USER_ID, MANAGER_ID",
        relation: "Team lead có thể thuộc một PM qua MANAGER_ID, nhưng không có TEAM_LEADER_ID riêng trên bảng nghiệp vụ.",
      },
      {
        scope: "Workflow",
        tone: "success",
        table: "P_PART_ASSIGNEE",
        columns: "PP_ID, USER_ID",
        relation: "Tổ trưởng thường theo dõi danh sách worker được phân công vào từng part.",
      },
      {
        scope: "Workflow",
        tone: "success",
        table: "PART_WORK_LOG",
        columns: "PP_ID, USER_ID, QUANTITY, CREATE_DATE",
        relation: "Theo dõi sản lượng công đoạn của worker theo ngày ghi nhận.",
      },
    ],
    gaps: [
      "Chưa có TEAM_LEADER_ID trực tiếp trên P_PART như bản mô hình cũ.",
      "Chưa có audit riêng cho việc đổi line lead hoặc điều chuyển worker.",
    ],
  },
  {
    key: "Worker",
    label: "Nhân viên",
    shortLabel: "Tác nghiệp sản xuất",
    tone: "primary",
    description: "Role worker được phản ánh mạnh nhất qua worker skill, assignment part và work log.",
    joinPath: "[ROLE] -> USER_ROLE -> [USER] + USER_WORKER_SKILL",
    touchpoints: [
      {
        scope: "Direct",
        tone: "primary",
        table: "USER_WORKER_SKILL",
        columns: "USER_ID, WS_ID",
        relation: "Gắn user với kỹ năng/chuyên môn thợ.",
      },
      {
        scope: "Direct",
        tone: "info",
        table: "[USER]",
        columns: "USER_ID, MANAGER_ID",
        relation: "Worker đi theo tuyến quản lý của team lead hoặc PM tùy cách tổ chức MANAGER_ID.",
      },
      {
        scope: "Direct",
        tone: "success",
        table: "CUTTING_NOTEBOOK_LOG",
        columns: "CP_ID, USER_ID, PRODUCT_QTY, IS_PAYMENT",
        relation: "Worker ghi log cắt, sản lượng và trạng thái thanh toán.",
      },
      {
        scope: "Direct",
        tone: "success",
        table: "P_PART_ASSIGNEE",
        columns: "PP_ID, USER_ID",
        relation: "Worker được gán vào từng part.",
      },
      {
        scope: "Direct",
        tone: "success",
        table: "PART_WORK_LOG",
        columns: "PP_ID, USER_ID, QUANTITY, CREATE_DATE, IS_PAYMENT",
        relation: "Worker ghi nhận sản lượng hằng ngày.",
      },
    ],
    gaps: [
      "Chưa có bảng lưu lịch sử điều chuyển worker giữa các part.",
      "Chưa có bảng năng suất tổng hợp theo ca hoặc theo line.",
    ],
  },
];

export function getAdminDbRoleOptions() {
  return ADMIN_DB_ROLE_BLUEPRINTS.map((role) => ({
    key: role.key,
    label: role.label,
    shortLabel: role.shortLabel,
    tone: role.tone,
    description: role.description,
  }));
}

export function getAdminDbRoleBlueprint(roleKey) {
  return ADMIN_DB_ROLE_BLUEPRINTS.find((role) => role.key === roleKey) || ADMIN_DB_ROLE_BLUEPRINTS[0];
}

export function getAdminDbLogSource(sourceKey) {
  return ADMIN_DB_LOG_SOURCES.find((source) => source.key === sourceKey) || null;
}
